### ISSUE TITLE
is is possible use cpu only? ~not use cuda

### ISSUE THREAD

**Issue by arafat5549** [MVIG-SJTU/AlphaPose#116]
is is possible use cpu only ~not use cuda

**Comment by lianghongkey** [comment]
you can try pytorch vision

**Comment by gaolaowai** [comment]
Anyone get CPU only working? Installed pytorch version, ran the "pip install -r requirements.txt" with no issues, then get the error (with webcam demo):

Loading YOLO model..
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=70 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "webcam_demo.py", line 49, in <module>
    det_loader = DetectionLoader(data_loader, batchSize=args.detbatch).start()
  File "/home/max/cvstd/learnopencv/AlphaPose/dataloader_webcam.py", line 122, in __init__
    self.det_model.cuda()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 249, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 182, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 249, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/aten/src/THC/THCGeneral.cpp:70

**Comment by gaolaowai** [comment]
For fun, went through the directory and ran:
"""sed -ie 's/\.cuda()/\.cpu()/g' *.py"""
and:
"""sed -ie 's/CUDA\=True/CUDA\=False/g' *.py"""

This roughly changed everything over to CPU, but now dealing with issues about being unable to serialize opencv VideoCapture object.

**Comment by amin07** [comment]
Possible. you have to comment out all statement with .cuda() and also make CUDA=False in some calls. Follow your errors and fix one file at a time.

**Comment by darkoob12** [comment]
> For fun, went through the directory and ran:
> """sed -ie 's/.cuda()/.cpu()/g' *.py"""
> and:
> """sed -ie 's/CUDA=True/CUDA=False/g' *.py"""
> 
> This roughly changed everything over to CPU, but now dealing with issues about being unable to serialize opencv VideoCapture object.

this worked for me. thanks.

**Comment by xiaoweiChen** [comment]
As above said, this repo is not with/without GPU or CUDA option, it default think you have CUDA device, so you should modify the source code to make the test on CPU part.

**Comment by arafat5549** [comment]
thx

**Comment by aashishsoni05** [comment]
can anyone let me know how can I run only CPU mode?

**Comment by gaolaowai** [comment]
> can anyone let me know how can I run only CPU mode?


"""sed -ie 's/.cuda()/.cpu()/g' *.py"""
and:
"""sed -ie 's/CUDA=True/CUDA=False/g' *.py"""

**Comment by leidawt** [comment]
Also , in <...>\AlphaPose\AlphaPose\SPPE\src\main_fast_inference.py you should replace line 61 with:         model.load_state_dict(torch.load('./models/sppe/duc_se.pth',map_location=lambda storage, loc: storage))
since the pth is at GPU version.
ref:https://discuss.pytorch.org/t/on-a-cpu-device-how-to-load-checkpoint-saved-on-gpu-device/349/3

**Comment by fenaux** [comment]
I try to run alphapose on Ubuntu cpu. If any one managed to do that, can you please give access to all the modification needed ? Many thanks

**Comment by nickgrealy** [comment]
I created a CPU-only Docker image, based on Ubuntu 20.04 (and the the source code modifications suggested above).

Details here -> https://github.com/nickgrealy/AlphaPose/blob/pytorch-cpu/docker/Dockerfile

**Comment by NeelayS** [comment]
> I created a CPU-only Docker image, based on Ubuntu 20.04 (and the the source code modifications suggested above).

Hey! Thanks for sharing the Docker image. However, the link seems to be broken as of now and I couldn't find it on your fork either (please let me know if I'm missing something)

**Comment by nickgrealy** [comment]
@NeelayS - sorry, I did some refactoring and moved stuff around the other day.

It's now here -> https://github.com/nickgrealy/AlphaPose/blob/pytorch-cpu/Dockerfile

**Comment by NeelayS** [comment]
> It's now here -> https://github.com/nickgrealy/AlphaPose/blob/pytorch-cpu/Dockerfile

Thank you !

**Comment by programmin1** [comment]
> I created a CPU-only Docker image, based on Ubuntu 20.04 (and the the source code modifications suggested above).
> 
> Details here -> https://github.com/nickgrealy/AlphaPose/blob/pytorch-cpu/docker/Dockerfile

Details where? Nothing there.

**Comment by nickgrealy** [comment]
@programmin1 - yep, the file got moved (covered in later comments). I've updated the original comment.

> I created a CPU-only Docker image, based on Ubuntu 20.04 (and the the source code modifications suggested above).
> 
> Details here -> https://github.com/nickgrealy/AlphaPose/blob/pytorch-cpu/docker/Dockerfile
> 
> # * * * PLEASE NOTE UPDATED LOCATION * * *
> https://github.com/nickgrealy/AlphaPose/blob/pytorch-cpu/Dockerfile
> 
> https://github.com/nickgrealy/AlphaPose/blob/pytorch-cpu/DOCKER.md

**Comment by programmin1** [comment]
Thanks. That seems to be just a starter 20.04 with the contents of Alphapose in the docker?
So the install instructions from the howto would still need to be run inside it?
I tried for a long time to set it up on a 18.04 on an Intel+Nvidia system and I'm not sure if that was the problem. The documentation seems wrong in areas. https://github.com/MVIG-SJTU/AlphaPose/pull/713

**Comment by nickgrealy** [comment]
Nope - not just a starter. The docker file is simply a convenience for running the project in a consistent (repeatable), isolated environment.

I made code changes - specifically I followed the instructions for a cpu ONLY build from here -> MVIG-SJTU#116 (comment)

You can see the changes in this commit: https://github.com/nickgrealy/AlphaPose/commit/89de78d947d7d4173f9094fd7fdf687e3f5d38ed

**Comment by adarbha** [comment]
> Nope - not just a starter. The docker file is simply a convenience for running the project in a consistent (repeatable), isolated environment.
> 
> I made code changes - specifically I followed the instructions for a cpu ONLY build from here -> #116 (comment). Plus fixed a few issues that cropped up along the way.
> 
> You can see the changes in this commit: [nickgrealy@89de78d](https://github.com/nickgrealy/AlphaPose/commit/89de78d947d7d4173f9094fd7fdf687e3f5d38ed)

This image doesn't seem to work for videos. There seem to be some basic path issues in the code where I get FileNotFoundErrors for weights and models video_demo.py tries to find.
I did not test if it works on images.

**Comment by nickgrealy** [comment]
> This image doesn't seem to work for videos. There seem to be some basic path issues in the code where I get FileNotFoundErrors for weights and models video_demo.py tries to find. I did not test if it works on images.

I was exclusively using it for videos, 1.5 years ago, and it worked then.

**Comment by EthannHongg** [comment]
The updated version indeed works. For those encountering the path issues, take a look at the .dockerignore file as it does not upload the pertaining model and weights to github. You can add the following at the end of dockerfile to automatically download them to your image
`RUN pip install gdown &&
    gdown 1D47msNOOiJKvPOXlnpyzdKA3k6E97NTC -O models/yolo/yolov3-spp.weights &&
    gdown 1OPORTWB2cwd5YTVBX-NE8fsauZJWsrtW -O models/sppe/duc_se.pth`
