### ISSUE TITLE
cpu-only install

### ISSUE THREAD

**Issue by korin-lf** [MVIG-SJTU/AlphaPose#863]
Thank you. I followed 4-7 from (https://github.com/MVIG-SJTU/AlphaPose/issues/817#issuecomment-840260684) and got it working on ubuntu 20.04.
Now I am on ubuntu 18.04 with no Nvidia card
I followed exactly all 2-8 instructions
python36, removed all cuda and installed cuda 10.1 and pytorch==1.7.1 torchvision==0.8.2 cpuonly -c pytorch

removed ext_modules=get_ext_modules(), from setup.py as I am on cpu only machine

Now I am getting :
File "/home/user/gesture_detect/gesture_detect/models/layers/dcn/deform_conv.py", line 11, in
from . import deform_conv_cuda
**ImportError: libcudart.so.10.0**: cannot open shared object file: No such file or directory

what is the possible way to resolve this? I tried with symlinks but no luck
thank you

**Comment by divastar** [comment]
All the problems : stack on inferense, undefined symbol of deform_conv_cuda
just spent my day with nothing
on all systems ubuntu 20.04 etc
Can someone clarify this install mess?
cuda 10.1 with what (pytorch 1.1?) gonna work?

**Comment by korin-lf** [comment]
Finally got it working on ubuntu 20.04
uninstalled all previous cuda, pytorch
started with python3.8  cuda 11.2 drive 460 gcc9.3.0 pytorch 1.8

**Comment by P3RI9** [comment]
Hi @korin-lf Thanks for your answer! Im meeting the same problem trying to install alphapose on a non-cpu machine. I have some questions:
1. Did you install cpuonly pytorch version for 1.8.1?
2. Did you merge this pull request git pull origin pull/592/head as its said https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/INSTALL.md?
3. Did  you comment get_ext_modules() line?
4. Did you use --gpus -1 when launching demo_inference?

Thanks for your reply!

**Comment by CCxiaoLL** [comment]
> Finally got it working on ubuntu 20.04
> uninstalled all previous cuda, pytorch
> started with python3.8 cuda 11.2 drive 460 gcc9.3.0 pytorch 1.8

How do you compile successfully on the high version CUDA

**Comment by divastar** [comment]
You just have to keep everything compatible all the versions of cuda Python
compiler etc

**Comment by Syndikat2** [comment]
Having the exact same problem. Been stuck trying to work around this issue for many days now..
